### ISSUE TITLE
evaJetpacks turn into evaParachutes

### ISSUE THREAD

**Issue by Zorbaq** [BrettRyland/BDArmory#154]
With latest BDA and KSP 1.11.2, jetpacks turn into parachutes or are deleted completely on scene load.

**Comment by BrettRyland** [comment]
This was a feature added in v1.4.2.2 as part of the Kerbal Safety option. Kerbals in craft spawned by BDA have the default inventory assigned and then the jetpack removed to reduce their weight (inspired by a weight-restricted round of Flying Circus).
> Remove the kerbals' jetpacks to save 45kg.
It should only occur on vessel spawning though, not scene load.

Is this undesirable?
I can make a slider option in the vessel spawning settings for this with values like "no change", "reset default", "parachutes only"?

**Comment by Zorbaq** [comment]
Apologies, I missed that in the changelog. I had this happen on an existing vessel after upgrading from 1.4.1 to 1.4.2.6 once, and then continuously even when I re-equipped the Kerbal with a new jetpack, performed EVA, reentered the vessel, saved and reloaded the game. The jetpack turned into a parachute on quickload. However, the vessel was normally spawned (VBA + launch) and had no BDA-related parts on it. The crews of brand new vessels spawned the ksp-way (runway, pad) are missing the jetpacks as well.

**Comment by BrettRyland** [comment]
OK, checking the code again, I see that the inventory reassignment is actually happening when Kerbal Safety gets enabled (toggling the option or starting a competition with it enabled), so it's probably being triggered by one of those conditions. Disabling Kerbal Safety in the general BDA settings ought to prevent it from occurring for now. I'll see what I can do tonight to make it configurable.

**Comment by BrettRyland** [comment]
I've added a slider that's visible in the "General Slider Settings" section when "Kerbal Safety" is enabled. It has options for "No Change", "Reset Default" and "Parachute Only" (default).
![Screenshot_20210317_213316](https://user-images.githubusercontent.com/18440126/111536259-5064d280-876a-11eb-8703-433862da1d6f.png)
I've pushed this as bugfix release v1.4.2.7.

**Comment by Zorbaq** [comment]
Very nice, thanks!
