### ISSUE TITLE
Multiple Turret Selection

### ISSUE THREAD

**Issue by AgitatedTofu** [BrettRyland/BDArmory#296]
When any rocket pod/turret or gun pod/turret is selected from the weapon manager menu, all other turrets activate and start following the cursor. Tried messing with many of the in-game settings but nothing helped.

**To Reproduce**
Place any combination of pods/turrets and a Weapon Manager on a vessel. Choose any pod/turret from the weapon list. All turrets should start following.

**Expected behaviour**
Only the selected group/weapon should be active

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/7585105/KSP.log)

**Comment by BrettRyland** [comment]
This is intended behaviour, introduced in v1.4.7.0.
> Allow turrets other than the current one to track the main target so they're ready to fire if the current one is unable to do so.
