### ISSUE TITLE
Aim Indicatior Drawing

### ISSUE THREAD

**Issue by AgitatedTofu** [BrettRyland/BDArmory#297]
**Describe the bug**
Rocket pods such as the Hydra and FFAR do not display the reticle properly; the green circle extends slightly ahead of the pod and does not show where the rockets will impact.

**To Reproduce**
Place rocket pods (not turrets) on a vessel with Weapon Manager module and select the pod(s).

**Expected behaviour**
The reticle should be drawn on the calculated impact site, not mid-air.
**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/7585118/KSP.log)

**Screenshots**

![ss1](https://user-images.githubusercontent.com/94875964/142953425-fdcb9ca4-85e4-4486-8a30-2f4093b9ebe3.png)
![ss2](https://user-images.githubusercontent.com/94875964/142953433-f24b5677-88f8-4bc2-ae73-4669a01ca8ea.png)

**Comment by BrettRyland** [comment]
OK, I can confirm that I get that too and it's not what it's supposed to be. I'll look into it.

**Comment by AgitatedTofu** [comment]
Thank you for the amazing work by the way!!

**Comment by 332505** [comment]
I got the similar problem when my vehicle is around the spawn point or the radar altitude is over 150 m.

**Comment by BrettRyland** [comment]
This should finally be fixed once-and-for-all in v1.5.5.0.
