### ISSUE TITLE
Scaling parts

### ISSUE THREAD

**Issue by rJacuu** [BrettRyland/BDArmory#346]
https://github.com/BrettRyland/BDArmory/issues/280

Would it be possible to make a separate .cfg file just for scales, so that changing scale wouldn't require opening every .cfg file of every part?

**Comment by BrettRyland** [comment]
This can be achieved through a relatively simple MM patch along the lines of
```
@PART[baha*|bd*] {
    @rescaleFactor *= n}
```
(you may need to adjust the `baha*|bd*` filter to match only the parts you want scaled).

Be aware that such a rescaling affects the model mesh size and attachnode locations (relative to the new model size) and may have some effect on drag (for parts without overrides in the cfg), HP and mass (depending on armour and material of the part) of the affected parts.
