### ISSUE TITLE
Cliking throught WM Gui

### ISSUE THREAD

**Issue by rJacuu** [BrettRyland/BDArmory#348]
When switching weapons in WM, rocket pods _[hydra, s8, ffar]_ are firing. Idk if its intended or not. 
Quick fix is changing fire button to something else than m1. 

Making them fire only in "trigger armed" mode would be nice, also other guns _[.50 cal, gau8... etc]_ could use this feature.

**Comment by BrettRyland** [comment]
This is fixed in dev.
