### ISSUE TITLE
RWR

### ISSUE THREAD

**Issue by rJacuu** [BrettRyland/BDArmory#355]
RWR appears to have a very large scale [180km at the gui's edge]. It's difficult to tell which direction the lock on is coming from until you're about 15-20 km away from the threat. It could be useful to scale it down to something more manageable.

**Comment by rJacuu** [comment]
https://imgur.com/a/FTwQC2J ss for reference

**Comment by BrettRyland** [comment]
The radar range can be adjusted via the hotkeys `RADAR_RANGE_UP` and `RADAR_RANGE_DN`, which you can set in the "Edit Inputs" section of the settings:
![Screenshot_20220420_214634](https://user-images.githubusercontent.com/18440126/164310878-f6dbac17-a01c-49e8-a47b-81150894adc3.png)
I've also added an option in dev to have the RWR display distances logarithmically.

**Comment by rJacuu** [comment]
Oh, i never noticed it changes the range of RWR too :D
