### ISSUE TITLE
IR missile seeker not finding any targets.

### ISSUE THREAD

**Issue by VenomiXeD** [BrettRyland/BDArmory#358]
**Describe the bug**
When using an IR missile for example a stinger from a pack or even the included AIM-9, it simply does not target any aircraft, it does do it when I do use the radar to slave the missile on to the target. I suspect there's a variable being -1 that shouldn't be -1 since none of the actual targeting search code actually runs because all of the 3 conditions are not met, and as such the actual seeker doesn't actually do anything. 

Some tests I did in game showed that no debug lines were shown since I was using debug lines enabled and according to the code, if debug lines are enabled there should be debug lines when I use the IR seeker, however no result.
![image](https://user-images.githubusercontent.com/32819948/166158688-a4a74423-5b57-4e30-8c4f-94835d5291da.png)
![image](https://user-images.githubusercontent.com/32819948/166158692-38784745-305d-47a2-82ae-197d46345868.png)

**To Reproduce**
Use any air-to-air IR guided missile, use an enemy aircraft and point the seeker, nothing will happen since the seeker does not actually work.

**Expected behaviour**
When pointing an IR missile against an aircraft, the seeker should lock on the target.

**Logs**
No results in logs.

**Screenshots**

**Additional context**
Air-to-air combat using IR missiles.

**Comment by BrettRyland** [comment]
Fixed in a previous release (v1.5.0.0 maybe?)
