### ISSUE TITLE
Animating parts

### ISSUE THREAD

**Issue by rJacuu** [BrettRyland/BDArmory#362]
Hi, is it possible to make a part with two animations? 
I'd like to make a russian 9M120 missile that has deployable fins, and then spins when it flies.

**Comment by BrettRyland** [comment]
I don't know much about the modelling side of things. You'd be better off asking SuicidalInsanity#2716 (or one of the others that do modelling) on the discord server https://discord.gg/yNpJDDvY

**Comment by rJacuu** [comment]
Thanks
