### ISSUE TITLE
AGM-88C won't lock onto Radars

### ISSUE THREAD

**Issue by LightlawX** [BrettRyland/BDArmory#388]
Hello, sorry to bother you with this. I have noticed that the AGM-88C HARM missiles do not seem to lock onto Radar sources. 

When I open the radar warning module I get the diamond shape for the radar sources but when I fire the HARM in range at the target it either fly's away from target and misses or gets about halfway there and explodes in air. Not exactly sure whats happening here but I can provided logs or videos if you need you them.

If I find a solution to my problem I'll post it here.

Thanks again for taking the time to look at this and sorry again about bothering you with this.

**Comment by BrettRyland** [comment]
The weapon manager on the vessel with the radar will automatically disable its radars if it detects an incoming anti-radiation missile. If the HARM loses its lock on the target, then it should fly to the last known GPS coordinates for the next 8s, after which it will disable guidance (this has now been changed in dev to continue guidance to the last known GPS coordinates).

Additionally, the AGM-88 HARM in BDArmory only targets ground radars (RWR Threat Types 0 and 5), so it depends on what you're firing at. I'm not sure about the C variant, which isn't part of stock BDArmory.

**Comment by LightlawX** [comment]
My bad I didn't mean to add the C variant to the AGM 88 I'm used to calling it that from playing Arma and DCS. So I seemed to have fixed my problem, I was most likely out of range of the radars with the HARM's and that is why they were probably acting weird. I think this can be closed now unless other people have similar problems.

**Comment by BrettRyland** [comment]
OK, closing then. :-)
