### ISSUE TITLE
Wheels can't be destroyed or damaged by all guns in BDArmory. 

### ISSUE THREAD

**Issue by bank2014** [BrettRyland/BDArmory#395]
Wheels can be destroyed only when they struck really hard on the ground
no explosions or bullets can damage it

**Comment by BrettRyland** [comment]
Correct. They use a different collider from every other part and are treated somewhat specially by KSP and BDArmory. This also means that they provide no protection from bullets or explosions. This may change in the future.
A selection of other special parts (such as the AI and WM modules) are also ignored by bullets and explosions.

**Comment by bank2014** [comment]
Ok
