### ISSUE TITLE
Targeting Pods Don't Change FOV

### ISSUE THREAD

**Issue by TheKerman21** [BrettRyland/BDArmory#422]
Describe the bug:
When trying to zoom in with any type of targeting pod, the FOV does not change at all, despite the symbology on the top right changing. If you look closely at the image below, you can see the slight image of the targeting pod zoomed in on the hangar, which indicates there is some sort of image layer of a zoomed FOV, but its opacity is very low.
![unknown](https://user-images.githubusercontent.com/34715258/186956366-0afdd58d-e39b-492a-8a05-fd742d025599.png)

To Reproduce:
Put any targeting pod on a craft, activate the targeting pod, and click on the + sign next to the x1 to attempt to zoom in

Expected behaviour:
By pressing the "+" or "-" buttons corresponding to zoom for the targeting pod, it is expected for the FOV to change

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9435019/KSP.log)

**Comment by BrettRyland** [comment]
This is due to some weird interaction with Scatterer. Reportedly, setting scatterer settings to "integrated" fixes that (I don't use Scatterer though, so that's second-hand info).

**Comment by TheKerman21** [comment]
That seemed to fix it, thank you for the support.
