### ISSUE TITLE
AI exceeds AoA limit

### ISSUE THREAD

**Issue by TheKerman21** [BrettRyland/BDArmory#425]
**Describe the bug**
The AI likes to exceed the AoA limit set by the AI flight computer, as well as by other mods such as AtmosphereAutopilot. In the first turn when a dogfight competition starts and other sharp turns, the AI pulls at least 60 AoA when I set the limiter to 25 degrees, which greatly hinders aircraft stability.

**To Reproduce**
I used a pretty standard aircraft with CoL slightly behind CoM.
I tested it with 2 settings:
1) PID: 12, steering correction: 0.1, steering dampening: 6
2) PID: 6, steering correction: 0.1, steering dampening: 3

In both cases, the AI exceeded set AoA limits.

**Expected behaviour**
Expected that AoA limits would limit the AI to not pull over the set AoA limit.

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9464974/KSP.log)

**Screenshots**
Test 1:
![image](https://user-images.githubusercontent.com/34715258/187781355-eec85a11-bac8-4136-8084-60d2f1408ed3.png)
![image](https://user-images.githubusercontent.com/34715258/187781468-a97a1511-6b0d-4462-b411-3f0f86a1e3c4.png)
You can see how its pulling drastically waaaay more AoA than whats its supposed to. Test 2 provided similar results

**Comment by BrettRyland** [comment]
This is a known issue that we're currently looking at. The AoA and G-load limits are rather ancient sections of BDArmory's codebase that we'll hopefully get around to overhauling after the next release.

**Comment by TheKerman21** [comment]
Thank you. Do you have an ETA towards next release?

**Comment by BrettRyland** [comment]
Hopefully within the next day or two.

**Comment by TheKerman21** [comment]
Awesome, looking forward to it.
