### ISSUE TITLE
CKAN identifier bug

### ISSUE THREAD

**Issue by Iamnotdead9942** [BrettRyland/BDArmory#428]
**Describe the bug**
BDArmory+ conflicts with BDArmoryContinued, even if only one is installed

**To Reproduce**
Install BDArmory+ through CKAN

**Logs**
N/A issue is through CKAN

**Screenshots**
![image](https://user-images.githubusercontent.com/113039431/188901752-357b0dc6-df99-44c6-9990-8fc7b051f570.png)

see that BDA+ is identified as BDArmory for runway project, conflicting it with BDAc

**Comment by BrettRyland** [comment]
This is an issue with CKAN, not BDArmory.
CKAN can do weird things at times, but I suspect what's going on here is that it's looking at an existing BDArmory folder and mis-identifying it as BDAc for some reason. You could try removing the GameData/BDArmory folder and reinstalling it. Make a backup of your settings in the GameData/BDArmory/PluginData folder first if you want to keep your current settings though.

**Comment by BrettRyland** [comment]
Closing due to being a CKAN issue, not a BDA+ issue.
