### ISSUE TITLE
AI does not use weapons in stationary mode; permanent stranded status

### ISSUE THREAD

**Issue by swg-wl** [BrettRyland/BDArmory#453]
Under any conditions, any vehicle in stationary mode instantly gets into a stranded status, which prevents AI from using weapons

<img width="518" alt="Screenshot" src="https://user-images.githubusercontent.com/86483750/201619077-7ebf7d18-8316-4c65-a079-d520b207c5b4.png">

**Comment by BrettRyland** [comment]
The stationary mode of the surface AI isn't really meant to do much and you can get pretty much the same behaviour you'd expect from a stationary AI by simply removing the surface AI. However, I'll add in some checks to disable most of the movement logic, which should fix this.

**Comment by BrettRyland** [comment]
Improvements to the stationary mode of the surface AI are in v1.5.5.0, which should fix this.
