### ISSUE TITLE
Active Vessel will not fire guns while in Competition Mode

### ISSUE THREAD

**Issue by zpjester** [BrettRyland/BDArmory#456]
**Describe the bug**
See the title. The active vessel refuses to fire its guns using Guard Mode while competitions are active, and seems to occasionally not fire when Guard Mode is toggled on manually. Discovered with @Sidestrafe2462

**To  @Reproduce**
Start a competition with 2 or more planes. The active vessel at any given time will not shoot, even when lined up perfectly for the shot. 

**Expected behaviour**
Both planes will shoot.

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10095721/KSP.log)

**Comment by BrettRyland** [comment]
Yep, I broke something... fixing it now.

**Comment by BrettRyland** [comment]
This should be fixed in v1.5.5.1.
