### ISSUE TITLE
Game crashing on startup

### ISSUE THREAD

**Issue by Tonkyboi1** [BrettRyland/BDArmory#459]
**Describe the bug**
Game crashing at startup because according to the logfile, in some cfg files some stuff is missing
**To Reproduce**
Please provide the steps to reproduce the behaviour:
Get BDA+ And a whole lotta extension mods for BDA+, Start up game
**Expected behaviour**
Game loads properly WITHOUT CRASHING
**Logs**
Please attach your `<KSP Directory>/KSP.log` file.
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10179881/KSP.log)
**Additional context**
I can provide the config files I found in the folder if you request so you can fix this issue (Hopefully?)

**Comment by Tonkyboi1** [comment]
Please reply at least a little fast as I am a little impatient but won't get mad

**Comment by BrettRyland** [comment]
Your log shows no problems directly related to BDArmory other than that the bullet definitions from the KBF mod haven't been updated.
The log does cut off fairly early in KSP's start-up process, which I assume is from the crash. If you can locate the Player.log file (see this post https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/), then it may contain the last lines from before KSP crashes, which might indicate what the problem is. Otherwise, the only was to find out which mod is causing the problem is by systematically removing them.

**Comment by Tonkyboi1** [comment]
[Player.log](https://github.com/BrettRyland/BDArmory/files/10180119/Player.log)
^Here ya go

**Comment by Tonkyboi1** [comment]
It IS BDArmory+, Because all them errors in console? BDArmory+, They're because some configs are missing values, Please replace these configs for me or fix them, CFGs provided cause I'm pretty sure its the CFG's.
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10180818/KSP.log)
[BD_Rockets - Copy.txt](https://github.com/BrettRyland/BDArmory/files/10180831/BD_Rockets.-.Copy.txt)
[BD_Armors - Copy.txt](https://github.com/BrettRyland/BDArmory/files/10180832/BD_Armors.-.Copy.txt)
[BD_Bullets - Copy.txt](https://github.com/BrettRyland/BDArmory/files/10180833/BD_Bullets.-.Copy.txt)
[BD_Materials - Copy.txt](https://github.com/BrettRyland/BDArmory/files/10180834/BD_Materials.-.Copy.txt)
[BD_Mutators - Copy.txt](https://github.com/BrettRyland/BDArmory/files/10180835/BD_Mutators.-.Copy.txt)
^Files, Take a look at them and see if anything's wrong

**Comment by BrettRyland** [comment]
Those errors in the log aren't the cause of KSP crashing, they're warnings for the creators of the other mods (i.e., KBF, NSI and NKD) that their bullet definitions don't contain the appropriate fields for this version of BDArmory+ and the default values are being used instead.

**Comment by Tonkyboi1** [comment]
Oh, whoops

**Comment by Tonkyboi1** [comment]
Noticed something, It crashes at this part
![image](https://user-images.githubusercontent.com/87203360/206328386-15494495-08aa-4317-998c-b66a03441efe.png)
Can I just delete the file as a crappy workaround?

**Comment by BrettRyland** [comment]
The model files aren't likely to be the cause of the issue. It's just the last message showing what's been processed by the loader. You need to remove some of the mods until you can start up KSP without it crashing and then add them back one or a few at a time to figure out which one is causing the crash.

**Comment by Tonkyboi1** [comment]
What if it's a mod I want to keep?

**Comment by BrettRyland** [comment]
The first step is to figure out which mod (or mods) is causing the issue. Once you know that, you can see whether there's some way to fix it. If it can't be fixed then you'll have to decide whether you can live without that mod or not or find some other solution.

**Comment by Tonkyboi1** [comment]
It seemed to be B9Aerospace Procedural Wings, I didn't know how to use it anyway, Moved to my temporary storage folder for mods I think can be fixed somehow, Thanks!
