### ISSUE TITLE
PRE doesn't work 2

### ISSUE THREAD

**Issue by Red1949** [BrettRyland/BDArmory#466]
Continuation of: https://github.com/BrettRyland/BDArmory/issues/454

Well, I have some free time so:
Few days ago I’m reinstalled KSP by deleting ALL files except Steam Cloud files like saves and etc. (Of course I’m copied mods)
Maybe I’m explained everything to you wrongly. Disappeared not vessel itself, I mean HUD (Icon of vehicle) of this vehicle is disappearing, EVEN VANILLA ONE. Well, when I reinstalled KSP, I fixed vanilla HUD, now only BDA HUD disappearing.
I noticed this problem appeared when 1.12.4 was released and when I turned off Squad launched by steam launch option. Today I will try to play on 1.12.3. and play with launcher to check what one of these (or even both are not) causes problem and tell you about it. Thanks a lot.
Sorry for my eng again.

Updated 12.28.2022: Not clear reinstall of everyting you can possibly reinstall, not changing of veriosn, not even enable of launcher didn't help. Here video is: https://drive.google.com/file/d/1l28cSMLvegy86gQ9M3kd1laGc6aAd3eu/view?usp=sharing.

Help me please...

**Comment by BrettRyland** [comment]
I am on holiday until mid-January so I won't be able to look at anything until then.

**Comment by Red1949** [comment]
Okay I'll wait.

**Comment by Red1949** [comment]
Oh well, you know what? I made it. KSP is fixed. How I did this? I'm again reinstalled KSP and mods and disabled option for removing squad launcher. (like in this video https://youtu.be/SzniLkUUPEI)
Anyway KSP is fixed and now I'm satisfied.
Also personal gratitude to you for Language localization. Peace, my friend.
