### ISSUE TITLE
Visual/Sound errors with missiles and guns

### ISSUE THREAD

**Issue by NaeNaeG0blin** [BrettRyland/BDArmory#478]
When firing missiles/rockets no smoke/fire trails appear after the missiles and when firing guns no tracers appear and no sound plays for either. Settings don't seem to have anything that can enable these features so I'm assuming its a bug

**Comment by BrettRyland** [comment]
You most likely have a broken install of BDA+. Try reinstalling it. If it still has issues after that, then examine the KSP.log file to see what is broken.
