### ISSUE TITLE
"No Weapon Manager Found" Issue when Procedural Missile Parts are on the Aircraft.

### ISSUE THREAD

**Issue by SireSnek** [BrettRyland/BDArmory#491]
**Describe the bug**
Despite there being a Weapon Manager on the Craft, the Weapon Manager GUI says it is not found, this only happens to vessels that have Procedural Missiles on them. If there are no Procedural Missiles, it works just fine, and upon jettisoning the missiles, and waiting a small while the Manager works again.

**To Reproduce**
Slap on some Procedural Missiles from the Procedural Missile Parts mod (https://github.com/jrodrigv/BDModularMissileParts)

**Expected behaviour**
The Weapon Manager being recognized & working while Procedural Missiles are on my Aircraft.

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10948796/KSP.log)

**Screenshot**
Screenshots: https://imgur.com/a/2pOFpSE

**Comment by BrettRyland** [comment]
Hi, PR #492 should fix the issue of the weapon manager not showing up once it gets merged in. However, your log is showing a large number of errors and exceptions from the NAS mod, which could also be causing a variety of issues.

I've attached a build of the BDArmory.dll with PR #492 included if you'd like to test it before the next BDA+ release is made.
[BDArmory.zip](https://github.com/BrettRyland/BDArmory/files/10955246/BDArmory.zip)
