### ISSUE TITLE
Heat-seeking missiles are unrealistically ineffective.

### ISSUE THREAD

**Issue by Di0so** [BrettRyland/BDArmory#493]
Aim 9 and other heat-seeking missiles are unrealistically ineffective.

Put two aircraft one flying in a straight line 
put a chase aircraft with a heat-seeking missile
then fire the missile

When the heat-seeking missiles fly toward the target and the fuze on the missile doesn't work and thus it does not destroy the target

I provided a video of the problem
and to be clear the missile does hit but very very rarely.

https://youtu.be/tm3wh6SfK7o

[KSP.zip](https://github.com/BrettRyland/BDArmory/files/11048671/KSP.zip)
wh6SfK7o

**Comment by megaferrari** [comment]
First, that is a beautiful modeled planes, second you can edit the missile in what do you like, i had this problem of the missile missing the target for like 2 meters and don't going off, you can set not only on missile config but also on hangar DetonateAtMinimumDistance to true and the said minimum detonation distance. you can also tweak fuze, guidance and engine fail chance at missile config, take a look at inside your gamedata on bdarmory  'BDArmory\Parts\sidewinder\sidewinder.cfg' it come with stock config and comments on what changes what

**Comment by Di0so** [comment]
OK so problem fixed, very please now!

**Comment by Di0so** [comment]
OK, issue fixed with the latest update, very pleased.
