### ISSUE TITLE
I cannot place any weapons without either the game glitching and causing everything to not work, or the weapons and radars won't let me place them

### ISSUE THREAD

**Issue by FurryDestroyer29** [BrettRyland/BDArmory#498]
I can only place three of the items and none of them are weapons themselves, radars, ammo, or anything weapon related besides the tank. I've constantly been searching for something like a config for it like the Environmental Visual Enhancement mod needs, but I found nothing yet. 

Is there anything I need to download to assist the BDarmory mod, like a config or something?

**Comment by FurryDestroyer29** [comment]
> This sounds like your KSP install is broken (mods not installed correctly, etc.), however, without a KSP.log file, there is nothing I can examine to tell you precisely what the issue is. BDArmoryPlus depends on the mods [Module Manager](https://forum.kerbalspaceprogram.com/index.php?/topic/50533-18x-112x-module-manager-421-august-1st-2021-locked-inside-edition/) and [Physics Range Extender](https://forum.kerbalspaceprogram.com/index.php?/topic/158344-ksp-1122-physics-range-extender-v1210-04-sep-2021/), as stated on the SpaceDock page https://spacedock.info/mod/2487/BDArmory%20Plus#info. If you use CKAN to install mods, it will install the dependencies for you automatically.

Oh, the Physics Range Mod is a dependency. This helps so much, thank you!

**Comment by BrettRyland** [comment]
With the exception of ModuleManager, mods are supposed to be extracted into their own folder in `KSP/GameData` folder like so:
![Screenshot_20230403_231028](https://user-images.githubusercontent.com/18440126/229628384-bba1df9d-2f5f-42ba-a79b-dcd79429572e.png)
Mods shouldn't be in other mods folders.

**Comment by FurryDestroyer29** [comment]
I got the Physics Range Extension mod and I've been had Module Manager and the game still won't let me place any of the weapons, only the rocket tubes and stuff.

**Comment by BrettRyland** [comment]
Post the KSP.log file from the main KSP folder.

**Comment by BrettRyland** [comment]
Yes. It contains the information needed to debug what's going wrong in your install.

**Comment by FurryDestroyer29** [comment]
"C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP.log"

**Comment by FurryDestroyer29** [comment]
oh i did it wrong

**Comment by BrettRyland** [comment]
If it's large, you might need to zip it.

**Comment by FurryDestroyer29** [comment]
Yea that's a good idea because I just lagged out like 3 times because it was too large

**Comment by FurryDestroyer29** [comment]
"C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP.zip"

**Comment by FurryDestroyer29** [comment]
Oops my bad.

**Comment by FurryDestroyer29** [comment]
[KSP.zip](https://github.com/BrettRyland/BDArmory/files/11142719/KSP.zip)
And there it is.

**Comment by FurryDestroyer29** [comment]
there is my log

**Comment by BrettRyland** [comment]
OK. It looks like you're missing large parts of the BDArmory mod. You have something else called `BahaTurret` in `Kerbal Space Program\GameData\BDArmory\Plugins\BahaTurret.dll` and a number of parts from BDArmory, but the main components are missing. I suspect that the BDArmory you downloaded was from some ancient version by BahamutoD. You should remove the BDArmory folder, then re-download and install BDArmory from https://spacedock.info/mod/2487/BDArmory%20Plus#info or via CKAN.

**Comment by FurryDestroyer29** [comment]
Well that's weird. Thank you for letting me know.

**Comment by FurryDestroyer29** [comment]
It successfully works, thank you so much for your time used to help me!
