### ISSUE TITLE
Version 1.6.0.1 bug

### ISSUE THREAD

**Issue by TheUnluckiestOne** [BrettRyland/BDArmory#503]
**Describe the bug**
I have no idea if this is affecting other people, but with this specific version I can't seem to launch missiles, either manually or through Action groups.

**To Reproduce**
use Version 1.6.0.1, have a plane with at least 1 missile, equip the weapon manager, bind fire missile, launch, attempt to use bind.
**Expected behaviour**
What should happen, if this does affect others, is that the missile should not be able to fire, either using the action group bind or from manually getting it to launch.

**Logs**
(probably not needed, but if so just let me know and i'll get a log.

**Screenshots**
N/A

**Additional context**

**Comment by BrettRyland** [comment]
This works for me. Please enable "Debug Missiles" in the debug settings and supply a log file.
![Screenshot_20230410_183832](https://user-images.githubusercontent.com/18440126/230948082-efdb19df-620f-4ee3-a227-72403a47db0d.png)

**Comment by TheUnluckiestOne** [comment]
[Player - Copy.log](https://github.com/BrettRyland/BDArmory/files/11192323/Player.-.Copy.log)
KSP log, x64

**Comment by BrettRyland** [comment]
This should now be fixed in v1.6.0.2.

**Comment by TheUnluckiestOne** [comment]
Thanks
