### ISSUE TITLE
AI VTOL Pilot Problem

### ISSUE THREAD

**Issue by Di0so** [BrettRyland/BDArmory#505]
I have been experimenting with helicopters so naturally I tried the AI Vtol Pilot, now the problem is, it can't control the vessel properly, and when you switch to another vessel it completely loses it and crashes, 

Set up 2 vessels, 1 on the ground and one in the air ( the helicopter ) now turn on its guard mode and make the ai try to destroy you.

The vessel in the air ( the helicopter ) will presumably face the ground target on its side, therefore not being able to destroy the target, and when you switch to that ground target it completely loses control and crashes, in rare cases the vessel in the air ( the helicopter ) would sometimes just fly over it if ever, and extend out and do the same thing over and over,

here is a visual demonstration to make it easier to understand.

https://youtu.be/JnB0pseLMlQ

* CONTEXT: THE ENGINE USED IN THE HELICOPTER IN THE VIDEO IS USING THE 'AIRPLANE PLUS' MOD *

**Comment by BrettRyland** [comment]
The engine you're using uses the firespitter bladed engine module (`FSengineBladed`), which the firespitter mod has unfortunately hard-coded to only be controllable if it's the active vessel (https://github.com/snjo/Firespitter/blob/master/Firespitter/engine/FS%20engine%20modules/FSengineBladed.cs#L224). If you change it for an engine that doesn't use that module, then it ought to work.

**Comment by Di0so** [comment]
hmm, would it ever be possible

**Comment by Di0so** [comment]
hmm, would it ever be possible yo make a workaround for this, and ive tested a different mod with a new engine (CWA) and for some reason it does do work and the ai manages to control the craft WITHOUT crashing, but as stated it would just fly over it if ever, and extend out and do the same thing over and over.

**Comment by BrettRyland** [comment]
It could be possible to implement the functionality that should be being called in that function, but it would be a fairly major hack that would likely break if ever the FireSpitter mod got updated and likely wouldn't be very performant. However, the VTOL AI is really something that one of the other devs put together based on the surface AI with some relatively minor changes, but didn't get that far with it, so it isn't really that functional.

**Comment by Di0so** [comment]
> It could be possible to implement the functionality that should be being called in that function, but it would be a fairly major hack that would likely break if ever the FireSpitter mod got updated and likely wouldn't be very performant. However, the VTOL AI is really something that one of the other devs put together based on the surface AI with some relatively minor changes, but didn't get that far with it, so it isn't really that functional.

So are you actually planning to give the BDa VTOL AI Pilot some functionality? and could maybe perhaps try to fix the issue with the firespitter? maybe like a plugin where it would trick the firespitter into thinking that the vessel is active?

**Comment by BrettRyland** [comment]
> So are you actually planning to give the BDa VTOL AI Pilot some functionality? and could maybe perhaps try to fix the issue with the firespitter? maybe like a plugin where it would trick the firespitter into thinking that the vessel is active?

The VTOL AI is not high on the priority list, so probably not. As I said, it was another dev that implemented it more as an experiment, but he hasn't done much dev stuff lately.
It's not possible to trick the firespitter engine into thinking that it's the active vessel, that's a core part of KSP that would likely break a lot of things. A better option would be for somebody to take over the firespitter mod and fix it there, but I have more than enough on my plate already.

**Comment by Di0so** [comment]
Ok, issue closed for now.
