### ISSUE TITLE
Weapon Manager Stops working when a vehicle goes out of and back into physics range

### ISSUE THREAD

**Issue by kman11223344** [BrettRyland/BDArmory#540]
**Describe the bug**
Whenever a vehicle with a weapon manager leaves and goes back into physics range, the weapon manager GUI when switching to that vehicle says "No Weapon Manager found". I have tried this on a completely fresh install with only BDA+ and it's dependencies, and it is still an issue. I can right-click the manager and hit "Open GUI" or "ToggleGUI" and it will just open/close the GUI. It does not recognize that the manager is there. I am using v1.6.3.0 on a KSP 1.12.5.3190 save.

**To Reproduce**
Have two vehicles, both with a weapon manager. Fly/Drive one vehicle so the other is out of physics range (I turned down the physics range for the example shown, but it does this at any physics range). Move towards that vehicle again so it is back in physics range. Switch to the stationary vehicle. 

**Expected behaviour**
The weapon manager GUI will say "No Weapon Manager found", as shown in the screenshot. 

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/11940879/KSP.log)

**Screenshots**
![screenshot1](https://github.com/BrettRyland/BDArmory/assets/34407449/45938099-dc76-41b7-9e5b-f5612e82f9e3)

**Additional Context**
I am not sure if this would effect it, but I have also set "TerrainExtenderEnabled" to "False" in the settings.cfg for PRE because of a separate issue where whenever a I would enter physics range, it would teleport whatever I had on the ground into the air kilometers away from where it was. That issue was fixed by changing that setting, but I do not know if that could cause this issue with the weapon manager.

**Comment by BrettRyland** [comment]
Huh, weird. I'll look into it. Having `TerrainExtenderEnabled` set to `True` in the PRE settings doesn't seem to affect it.

**Comment by BrettRyland** [comment]
Found and fixed the issue in dev, so it'll be fixed in the next release. The vessel's modules in BDA's internal registry just needed rescanning when the vessel got reloaded.

**Comment by Di0so** [comment]
When will the next release be?

**Comment by BrettRyland** [comment]
Just now :smile:
