### ISSUE TITLE
Modular Missile not guiding or starting engine

### ISSUE THREAD

**Issue by Duckk29** [BrettRyland/BDArmory#565]
Modular Missile doesn't guide or start engine when launched

This happens when I have a lock, If I don't have any lock the engine does start

[KSP.log](https://github.com/BrettRyland/BDArmory/files/13178147/KSP.log)

Video
https://streamable.com/97tdtu

**Comment by BrettRyland** [comment]
OK, I see a bunch of errors and exceptions in the log and we can reproduce them and a few more locally, so we should be able to get them fixed.

**Comment by Duckk29** [comment]
Yeah I have noticed a whole load related to BDArmory.

**Comment by Duckk29** [comment]
I have installed the latest update and the engine is starting now but the missile still doesnt seem to be guiding.

**Comment by Duckk29** [comment]
Ok so I have just noticed on the navball that the missile seems to think It's facing backward. Im not sure if this could be part of the Issue?
