### ISSUE TITLE
Ability to search BDA weapon parts in the VAB/SPH

### ISSUE THREAD

**Issue by sam25544** [BrettRyland/BDArmory#586]
A lot of the time when a lot of BDA part mods are installed it's tedious to find a specific part in the VAB/SPH using just the categories system. It would be nice to have the option of including BDA-module parts in search results to make it easier. It would probably be good to have it be toggleable so that we could avoid cluttering search results if we don't want to. This would make it way easier to sort through and find specific parts when a lot of part mods are installed.

**Comment by BrettRyland** [comment]
This is now working in v1.6.10.0.
