### ISSUE TITLE
MULTIPLAYER

### ISSUE THREAD

**Issue by pavankay** [BrettRyland/BDArmory#593]
I would love if you added multiplayer to this updated mod. I have been playing BDA multiplayer with friends for some time but cant stand the amount of bugs. I also love the new BDA+ updates and fixes you mad. Please add multiplayer support

**Comment by BrettRyland** [comment]
Multiplayer would be very complicated to make and is not on the TODO list for the foreseeable future. Sorry.

**Comment by hustlerone** [comment]
I would consider looking what's been done on https://github.com/jrodrigv/BDAMultiplayer and try to improve upon it. Even if your implementation has a LOT of overhead compared to BDAMultiplayer on the first iterations would be a massive win.
