### ISSUE TITLE
No missiles FX in 1.6.10

### ISSUE THREAD

**Issue by MrAliots** [BrettRyland/BDArmory#611]
**Describe the bug**
In the last version, missiles do not have any visual FX (smoke, thruster flames, torpedoes wake). FX works fine in 1.6.9.

**To Reproduce**
Shoot any missile or torpedoe in Kerbin atmosphere/water. There is no visual FX other than the stock KSP drag effect.

**Additional context**
Tested 1.6.9 vs 1.6.10 on a fresh KSP install, BDA and dependency installed with CKAN, no other mod.

**Comment by BrettRyland** [comment]
This should now be fixed in v1.6.10.1

**Comment by MrAliots** [comment]
Wow that was fast. Thanks you !
