### ISSUE TITLE
Unable to load aircrafts

### ISSUE THREAD

**Issue by mocholo** [BrettRyland/BDArmory#643]
KSP fails to load aircrafts by saying that modern r-60 radar and Advanced.cam are missing

I'm only have installed bda+, bdaE, PRE and module manager in the lastest version. With this mods aircrafts which have bda pieces doesn´t load

https://drive.google.com/drive/u/0/folders/1KyCLvSWVotBBDbLfGe0J6z19W-lIrilt   <---- screenshots and ksp.log

**Comment by BrettRyland** [comment]
Those aren't from BDA+ or BDA-E.
According to kerbalx, the "modern r-60 radar" comes from the [Fishy Anti Missile Spam](https://spacedock.info/mod/2682/Fishy%20anti%20missile%20spam) mod, but I don't know which mod the "advanced.cam" comes from.
