### ISSUE TITLE
Missiles refuse to attach to attachment node on VLS cells, the quad and singular

### ISSUE THREAD

**Issue by Squashyfungus** [BrettRyland/BDArmory#667]
I expected the missile (in particular the RIM 66D), to attach to the node at the top of the VLS cell and fill in the cells, yet for whatever reason it refuses to do so.
![Screenshot 2023-12-28 174635](https://github.com/user-attachments/assets/07044007-3811-4f4e-a03e-7a0a22cbc877)
This screenshot I took last year in December, 
![Screenshot 2024-09-01 192116](https://github.com/user-attachments/assets/d6b85d23-594d-4b6d-b0cf-7ef77eb6c9eb)
and this screenshot I took more recently, so it has been an issue for quite a while.

**Comment by TheEva66** [comment]
I am having this issue as well any fix?

**Comment by TheEva66** [comment]
did you ever find a fix?

**Comment by SquashyFunguss** [comment]
Indeed I did, turns out they attach in a weird way, you attach them with the radial attachment node, might have to rotate it if it doesn't immediately attach. Also there's no need to create space to fit the VLS cell, you can clip it into a solid part and it will fire no problem.
