### ISSUE TITLE
Module "ClusterBomb" isn't working properly.

### ISSUE THREAD

**Issue by Nigadiay** [BrettRyland/BDArmory#679]
![image](https://github.com/user-attachments/assets/cdb90e9c-3470-49c9-af93-9fbb16edfc28)
I just copied this from the clusterbomb.cfg file, trying to create a cluster missile, this change in the missile.cfg file causes it to explode at the correct altitude but not deploy submunitions. In addition to that I didn't find any information about this in the developer wiki (https://github.com/BrettRyland/BDArmory/wiki). 
![image](https://github.com/user-attachments/assets/8a009060-02e9-4e38-aa5a-1d6b1f2aefcc)
![image](https://github.com/user-attachments/assets/9150950f-7a52-415c-9c5b-e1ec39104e32)
^Maybe I need to change something in thoose parts of confing, but I don't know which ones.
I will be grateful if you can help me in this matter.

**Comment by BrettRyland** [comment]
Cluster missiles already exist in BDA-E (https://github.com/BrettRyland/BDArmory-Extended/tree/main/BDArmoryExtended/Parts/Missiles/ClusterMissile). If you're actually trying to make a cluster missile, then you should be basing your part off of that one instead.

If, on the other hand, you're simply trying to create a variant of the cluster bomb, then the `ClusterBomb` class looks for transforms in the model with the name "submunition", which are what are detached and set active when the cluster bomb detonates at the specified altitude.
