### ISSUE TITLE
Cruise missiles can't be launched,can only be launched after switching to guard mode

### ISSUE THREAD

**Issue by F8fate** [BrettRyland/BDArmory#690]
**Describe the bug**
As the title says.

**To Reproduce**
1.Equipped with cruise missiles
I'm using the  BDArmory built-in RBS-15 missile.

2.deploy a hostile,Input coordinates,Try launching a missile manually.

**Expected behaviour**
Missiles cannot be launched at this time.

however

3.switching to guard mode
AI will successfully launch the missile

4.turn off guard mode,Try launching a missile manually.
Missiles can be launched normally

**Logs**
[KSP.log](https://github.com/user-attachments/files/17987145/KSP.log)

**Screenshots**
I uploaded a video.
https://youtu.be/UPcVaeQDEE4

**Additional context**
As you can see,at the third step, the GPS TARGET changes from the TARGET sent by the pod to the target itself,This GPS coordinates were acquired by the AI.In the fourth step, you manually launch the missile, and it will self-destruct.But that's another issue.

**Comment by BrettRyland** [comment]
Thanks. This should now be fixed in v1.8.0.1.

**Comment by F8fate** [comment]
This issue has been resolved,many thanks!
