### ISSUE TITLE
Rocket pods: Nullreference

### ISSUE THREAD

**Issue by Neros7** [BrettRyland/BDArmory#84]
Whenever a Rocket Pod Rocket explodes tons of NullreferenceExceptions are spamming the console

**Comment by BrettRyland** [comment]
Do you have a section of the log showing this?
Something like:
```
[ERR 21:37:45.923] Exception handling event onCollision in class BDACompetitionMode:System.NullReferenceException: Object reference not set to an instance of an object
  at BDArmory.Control.BDACompetitionMode.AnalyseCollision (EventReport data) [0x0005b] in <6182987da2f346b4995da37994e872f5>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <948fceea813942b7ac6b6d1b2dc2d0a3>:0 

[EXC 21:37:46.067] NullReferenceException: Object reference not set to an instance of an object
        BDArmory.Control.BDACompetitionMode.AnalyseCollision (EventReport data) (at <6182987da2f346b4995da37994e872f5>:0)
        EventData`1[T].Fire (T data) (at <948fceea813942b7ac6b6d1b2dc2d0a3>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:LogException(Exception)
        EventData`1:Fire(EventReport)
```
It's hard to debug it without more info.

**Comment by Neros7** [comment]
Sure;
[EXC 18:30:52.009] NullReferenceException: Object reference not set to an instance of an object
	BDArmory.FX.ExplosionFx.CreateExplosion (UnityEngine.Vector3 position, System.Single tntMassEquivalent, System.String explModelPath, System.String soundPath, BDArmory.Core.Extension.ExplosionSourceType explosionSourceType, System.Single caliber, Part explosivePart, System.String sourceVesselName, UnityEngine.Vector3 direction) (at <b74115b370f34f26aafc1ba19f387033>:0)
	BDArmory.Modules.Rocket.Detonate (UnityEngine.Vector3 pos) (at <b74115b370f34f26aafc1ba19f387033>:0)
	BDArmory.Modules.Rocket.FixedUpdate () (at <b74115b370f34f26aafc1ba19f387033>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Neros7** [comment]
https://mega.nz/file/jt5hHCqA#3cqOzAhsvE34yWP4l6kvhl-xnY1FnyfPj8pFs3m-DTk

**Comment by BrettRyland** [comment]
OK, I've found and fixed it in the dev branch.
It'll be in the next CKAN release, which should be quite soon as we're getting ready for another round of Runway Project.
